version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile-react
    image: react:latest
    ports:
     - "80:3000"
  springboot:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile-springboot
    image: springboot:latest
    ports:
      - "8080:8080"